const mongoose= require('mongoose');

const RestRoomSchema= new mongoose.Schema(
    {
        rrname:
        {
            type:String
        },
        image:{
            type:String
        },
        images:{
            type:Array
        },
        rating:{
            type:Number
        },
        location:{
            latitude:{
                type:String
            },
            longitude:{
                type:String
            },
            city:{
                type:String
            },
            state:{
                type:String
            }
        },
        address:{
            type:String
        },
        contact:{
            type:String
        },
        amenities:{
            sanitary_napkins:{
                type:Boolean
            },
            dustbin:{
                type:Boolean
            },
            nursing_room:{
                type:Boolean
            },
            clean_drinking_water:{
                type:Boolean
            },
            handwash:{
                type:Boolean
            }
        },
        comments:{
                userid:{
                    type:String
                },
                author:{
                    username:{
                        type:String
                    },
                    profilepic:{
                        type:String
                    }
                },
                rating:{
                    type:Number
                },
                comment:{
                type:String
            }
        }
    }
)

module.exports= mongoose.model('RestRoom',RestRoomSchema);